### ISSUE TITLE
Adding Attributes

### ISSUE THREAD

**Issue by confact** [smacker/libgit2.cr#5]
Hi!

I was planning to using this to read and create git attributes for repos but it seems to not be added yet.

Is it planned to do so yet and if not could you at least add the lib-linked class so can i do the rest.

**Comment by smacker** [comment]
hi. I added repo#attributes here:
https://github.com/smacker/libgit2.cr/commit/fc9bc12b5722e4996768582277eec6db0b6f9ab7

Feel free to PR any other methods you need.

**Comment by confact** [comment]
Thanks - That's what I needed.
